services:
  app:
    container_name: vuanem-data-service
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "8080:8080"
